//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: ShellyMission.ice
//  Source: ShellyMission.idsl
//  
//****************************************************************** 
#ifndef ROBOCOMPSHELLYMISSION_ICE
#define ROBOCOMPSHELLYMISSION_ICE
module RoboCompShellyMission
{
	interface ShellyMission
	{
		void setMission (string path);
	};
};

#endif
