// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `JoystickAdapter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <JoystickAdapter.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompJoystickAdapter__JoystickAdapter__sendData_name = "sendData";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompJoystickAdapter::upCast(::IceProxy::RoboCompJoystickAdapter::JoystickAdapter* p) { return p; }

void
::IceProxy::RoboCompJoystickAdapter::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompJoystickAdapter::JoystickAdapter>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompJoystickAdapter::JoystickAdapter;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompJoystickAdapter__JoystickAdapter__sendData_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompJoystickAdapter::JoystickAdapter* __del = dynamic_cast< ::IceDelegate::RoboCompJoystickAdapter::JoystickAdapter*>(__delBase.get());
            __del->sendData(data, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::begin_sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompJoystickAdapter__JoystickAdapter__sendData_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompJoystickAdapter__JoystickAdapter__sendData_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(data);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::end_sendData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompJoystickAdapter__JoystickAdapter__sendData_name);
}

const ::std::string&
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::ice_staticId()
{
    return ::RoboCompJoystickAdapter::JoystickAdapter::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompJoystickAdapter::JoystickAdapter);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompJoystickAdapter::JoystickAdapter);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompJoystickAdapter::JoystickAdapter::__newInstance() const
{
    return new JoystickAdapter;
}

void
IceDelegateM::RoboCompJoystickAdapter::JoystickAdapter::sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompJoystickAdapter__JoystickAdapter__sendData_name, ::Ice::Idempotent, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(data);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::RoboCompJoystickAdapter::JoystickAdapter::sendData(const ::RoboCompJoystickAdapter::TData& data, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompJoystickAdapter::TData& __p_data, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_data(__p_data)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompJoystickAdapter::JoystickAdapter* servant = dynamic_cast< ::RoboCompJoystickAdapter::JoystickAdapter*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->sendData(_m_data, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompJoystickAdapter::TData& _m_data;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompJoystickAdapter__JoystickAdapter__sendData_name, ::Ice::Idempotent, __context);
    try
    {
        _DirectI __direct(data, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompJoystickAdapter::upCast(::RoboCompJoystickAdapter::JoystickAdapter* p) { return p; }

namespace
{
const ::std::string __RoboCompJoystickAdapter__JoystickAdapter_ids[2] =
{
    "::Ice::Object",
    "::RoboCompJoystickAdapter::JoystickAdapter"
};

}

bool
RoboCompJoystickAdapter::JoystickAdapter::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompJoystickAdapter__JoystickAdapter_ids, __RoboCompJoystickAdapter__JoystickAdapter_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompJoystickAdapter::JoystickAdapter::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompJoystickAdapter__JoystickAdapter_ids[0], &__RoboCompJoystickAdapter__JoystickAdapter_ids[2]);
}

const ::std::string&
RoboCompJoystickAdapter::JoystickAdapter::ice_id(const ::Ice::Current&) const
{
    return __RoboCompJoystickAdapter__JoystickAdapter_ids[1];
}

const ::std::string&
RoboCompJoystickAdapter::JoystickAdapter::ice_staticId()
{
    return __RoboCompJoystickAdapter__JoystickAdapter_ids[1];
}

::Ice::DispatchStatus
RoboCompJoystickAdapter::JoystickAdapter::___sendData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompJoystickAdapter::TData data;
    __is->read(data);
    __inS.endReadParams();
    sendData(data, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompJoystickAdapter__JoystickAdapter_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendData"
};

}

::Ice::DispatchStatus
RoboCompJoystickAdapter::JoystickAdapter::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompJoystickAdapter__JoystickAdapter_all, __RoboCompJoystickAdapter__JoystickAdapter_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompJoystickAdapter__JoystickAdapter_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___sendData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompJoystickAdapter::JoystickAdapter::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompJoystickAdapter::JoystickAdapter::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompJoystickAdapter::__patch(JoystickAdapterPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompJoystickAdapter::JoystickAdapterPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompJoystickAdapter::JoystickAdapter::ice_staticId(), v);
    }
}
